name: diff_match_patch
version: 0.2.1
authors:
- Boris Kaul <localvoid@gmail.com>
- Neil Fraser <neil.fraser@gmail.com>
description: The Diff Match and Patch libraries offer robust algorithms to perform the operations required for synchronizing plain text.
homepage: http://github.com/localvoid/diff-match-patch
dev_dependencies:
  unittest: any
