name: diff_match_patch
version: 0.4.1
description: The Diff Match and Patch libraries offer robust algorithms to perform the operations required for synchronizing plain text.
homepage: http://github.com/jheyne/diff-match-patch

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: any
  pedantic: ^1.11.0
